### ISSUE TITLE
希望能同时发布编译好的程序包～

### ISSUE THREAD

**Issue by NetRube** [kaneawk/shadowsocksr-android#5]
这样就省去自己编译的麻烦了哈～

**Comment by kaneawk** [comment]
I'm very sorry, github's disk space is not enough.

**Comment by NetRube** [comment]
那有没其他的发布渠道没～

**Comment by kaneawk** [comment]
On my blog:https://www.htcp.net/2690.html

**Comment by NetRube** [comment]
咦～原来是泪大～失敬失敬～原来这个版本以前有装过～不知什么原因耗电很严重就给卸了～

**Comment by JieSmart** [comment]
我把这个项目拷贝下来，在本地编译不通，怎么个情况

**Comment by sorasoras** [comment]
@kaneawk  我也尝试 在本地编译这个 项目   过不了
git submodule update --init --recursive
error: no such remote ref 5d5914f00b8adefd383f66b8b352855ece22a1d7
Fetched in submodule path 'src/main/jni/libevent', but it did not contain 5d5914f00b8adefd383f66b8b352855ece22a1d7. Direct fetching of that commit failed.
直接手动 Libevent git  到src/main/jni/libevent

然后就
 尝试编译
sbt native-build clean android:package-release
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project
[info] Updating ProjectRef(uri("file:/C:/Users/Sora-beijin/Desktop/AN/shadowsocksr-android/project/"), "shadowsocksr-android-build")...
[warn]  module not found: org.scala-android#sbt-android;1.7.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0/1.7.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0/1.7.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Sora-beijin\.ivy2\local\org.scala-android\sbt-android\scala_2.12\sbt_1.0\1.7.2\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-android/sbt-android_2.12_1.0/1.7.2/sbt-android-1.7.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Sora-beijin\.sbt\preloaded\org.scala-android\sbt-android\1.7.2\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Sora-beijin/.sbt/preloaded/org/scala-android/sbt-android_2.12_1.0/1.7.2/sbt-android-1.7.2.pom
[warn]  module not found: com.timushev.sbt#sbt-updates;0.1.10
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.1.10/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.1.10/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Sora-beijin\.ivy2\local\com.timushev.sbt\sbt-updates\scala_2.12\sbt_1.0\0.1.10\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Sora-beijin\.sbt\preloaded\com.timushev.sbt\sbt-updates\0.1.10\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Sora-beijin/.sbt/preloaded/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn]  module not found: net.virtual-void#sbt-dependency-graph;0.8.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Sora-beijin\.ivy2\local\net.virtual-void\sbt-dependency-graph\scala_2.12\sbt_1.0\0.8.2\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Sora-beijin\.sbt\preloaded\net.virtual-void\sbt-dependency-graph\0.8.2\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Sora-beijin/.sbt/preloaded/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-android#sbt-android;1.7.2: not found
[warn]  :: com.timushev.sbt#sbt-updates;0.1.10: not found
[warn]  :: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scala-android:sbt-android:1.7.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.scala-android:sbt-android:1.7.2 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L1-2)
[warn]            +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L3-4)
[warn]            +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L5-6)
[warn]            +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.2: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2385)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.2: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found

开着 sstaps 也不行

**Comment by JieSmart** [comment]
你是用的什么系统进行编译的，Windows？Linux？mac？好像Windows不支持编译这个项目

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shing3232 <notifications@github.com>
发送时间: Friday, April 20, 2018 3:45:45 AM
收件人: kaneawk/shadowsocksr-android
抄送: JieSmart; Comment
主题: Re: [kaneawk/shadowsocksr-android] 希望能同时发布编译好的程序包～ (#5)


@kaneawk<https://github.com/kaneawk> 我也尝试 在本地编译这个 项目 过不了
git submodule update --init --recursive
error: no such remote ref 5d5914f00b8adefd383f66b8b352855ece22a1d7
Fetched in submodule path 'src/main/jni/libevent', but it did not contain 5d5914f00b8adefd383f66b8b352855ece22a1d7. Direct fetching of that commit failed.
直接手动 Libevent git 到src/main/jni/libevent

然后就
尝试编译
sbt native-build clean android:package-release
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project
[info] Updating ProjectRef(uri("file:/C:/Users/Sora-beijin/Desktop/AN/shadowsocksr-android/project/"), "shadowsocksr-android-build")...
[warn] module not found: org.scala-android#sbt-android;1.7.2
[warn] ==== typesafe-ivy-releases: tried
[warn] https://repo.typesafe.com/typesafe/ivy-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0/1.7.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0/1.7.2/ivys/ivy.xml
[warn] ==== local: tried
[warn] C:\Users\Sora-beijin.ivy2\local\org.scala-android\sbt-android\scala_2.12\sbt_1.0\1.7.2\ivys\ivy.xml
[warn] ==== public: tried
[warn] https://repo1.maven.org/maven2/org/scala-android/sbt-android_2.12_1.0/1.7.2/sbt-android-1.7.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn] C:\Users\Sora-beijin.sbt\preloaded\org.scala-android\sbt-android\1.7.2\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn] file:/C:/Users/Sora-beijin/.sbt/preloaded/org/scala-android/sbt-android_2.12_1.0/1.7.2/sbt-android-1.7.2.pom
[warn] module not found: com.timushev.sbt#sbt-updates;0.1.10
[warn] ==== typesafe-ivy-releases: tried
[warn] https://repo.typesafe.com/typesafe/ivy-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.1.10/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.1.10/ivys/ivy.xml
[warn] ==== local: tried
[warn] C:\Users\Sora-beijin.ivy2\local\com.timushev.sbt\sbt-updates\scala_2.12\sbt_1.0\0.1.10\ivys\ivy.xml
[warn] ==== public: tried
[warn] https://repo1.maven.org/maven2/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn] ==== local-preloaded-ivy: tried
[warn] C:\Users\Sora-beijin.sbt\preloaded\com.timushev.sbt\sbt-updates\0.1.10\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn] file:/C:/Users/Sora-beijin/.sbt/preloaded/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn] module not found: net.virtual-void#sbt-dependency-graph;0.8.2
[warn] ==== typesafe-ivy-releases: tried
[warn] https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.2/ivys/ivy.xml
[warn] ==== local: tried
[warn] C:\Users\Sora-beijin.ivy2\local\net.virtual-void\sbt-dependency-graph\scala_2.12\sbt_1.0\0.8.2\ivys\ivy.xml
[warn] ==== public: tried
[warn] https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn] C:\Users\Sora-beijin.sbt\preloaded\net.virtual-void\sbt-dependency-graph\0.8.2\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn] file:/C:/Users/Sora-beijin/.sbt/preloaded/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: UNRESOLVED DEPENDENCIES ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: org.scala-android#sbt-android;1.7.2: not found
[warn] :: com.timushev.sbt#sbt-updates;0.1.10: not found
[warn] :: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] Note: Some unresolved dependencies have extra attributes. Check that these dependencies exist with the requested attributes.
[warn] org.scala-android:sbt-android:1.7.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn] com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0)
[warn] net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] Note: Unresolved dependencies path:
[warn] org.scala-android:sbt-android:1.7.2 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L1-2)
[warn] +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn] com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L3-4)
[warn] +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn] net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\Sora-beijin\Desktop\AN\shadowsocksr-android\project\plugins.sbt#L5-6)
[warn] +- default:shadowsocksr-android-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.2: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[error] at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] at xsbt.boot.Using$.withResource(Using.scala:10)
[error] at xsbt.boot.Using$.apply(Using.scala:9)
[error] at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2385)
[error] at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] at sbt.Execute.work(Execute.scala:271)
[error] at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] at java.util.concurrent.FutureTask.run(Unknown Source)
[error] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error] at java.util.concurrent.FutureTask.run(Unknown Source)
[error] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error] at java.lang.Thread.run(Unknown Source)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.2: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found

开着 sstaps 也不行

―

**Comment by sorasoras** [comment]
啊 Windows 10不行啊 我用 Windows git 去编译。 如果有binary 就好了 但是已经找不到了

**Comment by JieSmart** [comment]
你有Linux的电脑或者mac吗？然后尝试一下


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shing3232 <notifications@github.com>
发送时间: Saturday, April 21, 2018 6:30:31 AM
收件人: kaneawk/shadowsocksr-android
抄送: JieSmart; Comment
主题: Re: [kaneawk/shadowsocksr-android] 希望能同时发布编译好的程序包～ (#5)


啊 Windows 10不行啊 我用 Windows git 去编译。 如果有binary 就好了 但是已经找不到了

―

**Comment by sorasoras** [comment]
拿个虚拟机试试咯
